version: "3"

networks:
  nginx-php8-postgres13-node:

services:
  # nginx
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php8-service
      - postgres13-service
    networks:
      - nginx-php8-postgres13-node

  # php
  php8-service:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php8-container
    ports:
      - "9000:9000"
      - "8010:8100"
    volumes:
      - ./app:/var/www/project
    networks:
      - nginx-php8-postgres13-node

  # postgresql
  postgres13-service:
    image: postgres:13.3-alpine
    container_name: postgres13-container
    ports:
      - "6432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    networks:
      - nginx-php8-postgres13-node

  # node
  node-service:
    image: node:latest
    container_name: node-container
    volumes:
      - ./app:/var/www/project
    working_dir: /var/www/project
    networks:
      - nginx-php8-postgres13-node

  # mail catcher
  mailer:
    image: schickling/mailcatcher
    ports:
      - 49165:1025
      - 49166:1080
    networks:
      - nginx-php8-postgres13-node
